### ISSUE TITLE
search for friends, friends of friends, and non-friends

### ISSUE THREAD

**Issue by techjeffharris** [adminion/off-the-record#11]
A user should be able to search for other user accounts.  Resulting users are grouped by their relationship to the searcher, FRIENDS, FRIENDS_OF_FRIENDS, PENDING_FRIENDS, and NON_FRIENDS, respectively.  Each user result should include a list of allowedInteractions.

**DEPENDS ON**
#21 

**TODO**
- [x] Search for a user's friends
- [x] Search for a user's friends-of-friends
- [x] Search for a user's pending friends
- [x] Search for a user's non-friends who's
- [x] Display buttons to end friendships and send/accept/deny/cancel friend requests if allowed

**Comment by techjeffharris** [comment]
finished preliminary implementation.  haven't pushed any code yet...
