### ISSUE TITLE
friend request transmission/approval/notification

### ISSUE THREAD

**Issue by techjeffharris** [adminion/off-the-record#12]
By default, all user accounts are private and undiscoverable.  Friend-based Relationship functionality allows finer-grained security configuration beyond all or nothing, by regulating access to user accounts based upon their relationship to other accounts and those other accounts' privacy preferences. 

Relationships are used to determine whether a given user is granted access to another user via Regulated Access Methods with respect to the Privacy Levels configured for those Access Methods by the requested user. 

While the server should be solely responsible for regulating access to all relationship-related requests, the user interface should evaluate the relationship/access preferences to determine what functionality should be made available.

### Relationships

* 0 - Not Friends
* 1 - Friends of Friends
* 2 - Pending Friends
* 3 - Friends

### Privacy Level

* 0 - Anyone
* 1 - Friends of Friends
* 2 - Pending Friends
* 3 - Friends
* 4 - No one

### Regulated Access Methods

* Search
* Profile
* Friend Requests
* Chat Invitations

**DEPENDS ON**
#21 

**TODO**

To implement friendship-based relationships, we must define the abilities to: 

- [x] Modify the Privacy Levels of a user's Access Methods
- [x] Determine the Relationship of two users
- [x] Determine whether a user is allowed to utilize a given Access Method to contact another user
- [x] Get a list of the ways that userA allows userB to interact with them
- [x] Determine whether or not two users have a pending request
- [x] Request another user's friendship
- [x] Review requests sent and received
- [x] Accept or Deny a received request
- [x] Cancel a sent request
- [x] End a friendship
- [ ] Blacklist another user
- [x] Publish/Notify a user's Online Presence
