### ISSUE TITLE
cache all users when starting the realtime module

### ISSUE THREAD

**Issue by techjeffharris** [adminion/off-the-record#27]
Having a single copy of each user in memory will be helpful in v1.0.0

**Pros**
* increase memory size far less than storing each user's friends' documents in an array in memory
* allow for in-memory
  * checking of who's allowed to interact with who
  * getting documents of friends, etc.
* each user then has only an array of friendIds rather than a hash of their friends' documents.

**Cons**
* fundamentally wrong for clustering (not going to happen in v1.0.0 anyway...)

**TODO**
- [x] get all users from the database when realtime module starts; add to cache
- [x] update the convos and users virtual properties in Users model to Arrays
- [x] when a user logs on, use ~~`data.user.Friendship.getFriends(userId, ...)`~~ `user.getFriends(...)`  to add each friend's ~~`_id`~~ `username` to the user's friends array
- [x] update other references to the user's friends to reflect the new structure

~~**DEPENDS ON**~~
~~* https://github.com/adminion/friends-of-friends/issues/43~~

**Comment by techjeffharris** [comment]
adminion/friends-of-friends#43 resolved, time to carry on!

**Comment by techjeffharris** [comment]
adminion/friends-of-friends#43 doesn't help as I switched to using the user's username as the key for all users (makes the contents of `user.friends` much more comprehensive to debug.
